export const UPDATE_SALARY = "UPDATE_SALARY";
export const UPDATE_SAVINGS = "UPDATE_SAVINGS";
export const UPDATE_SAVINGS_GOAL = "UPDATE_SAVINGS_GOAL";

export const UPDATE_CAREER = "UPDATE_CAREER";
export const UPDATE_ASSETS = "UPDATE_ASSETS";
export const UPDATE_INVESTMENTS = "UPDATE_INVESTMENTS";
export const UPDATE_SKILLS = "UPDATE_SKILLS";
export const UPDATE_ASSETS_DEBTS = "UPDATE_ASSETS_DEBTS";
export const UPDATE_SPIRIT = "UPDATE_SPIRIT";

export const PLAYER_MAKE_CHOICE = "PLAYER_MAKE_CHOICE";

export const FINISH_OUTCOME = "FINISH_OUTCOME";

export const SELECT_CAREER = "SELECT_CAREER";
export const UPDATE_SHARE_SPLIT = "UPDATE_SHARE_SPLIT";
export const UPDATE_INVEST_SETTING = "UPDATE_INVEST_SETTING";
export const UPDATE_MARK_SHARES_SELL = "UPDATE_MARK_SHARES_SELL";
